#ifndef LOCONETMONITOR_BUILD_NUMBER_H
#define LOCONETMONITOR_BUILD_NUMBER_H
#include <QString>


#define VER_BUILDNR 13483
#define VER_DATE 20170303
#define VER_HOUR 0
#define VER_MINUTE 8
#define VER_SECOND 21


#endif  // LOCONETMONITOR_BUILD_NUMBER_H
