#ifndef LOCONETMONITOR_BUILD_NUMBER_H
#define LOCONETMONITOR_BUILD_NUMBER_H
#include <QString>


#define VER_BUILDNR 13455
#define VER_DATE 20160517
#define VER_HOUR 0
#define VER_MINUTE 0
#define VER_SECOND 20


#endif  // LOCONETMONITOR_BUILD_NUMBER_H
