#ifndef LOCONETMONITOR_BUILD_NUMBER_H
#define LOCONETMONITOR_BUILD_NUMBER_H
#include <QString>


#define VER_BUILDNR 13484
#define VER_DATE 20170916
#define VER_HOUR 17
#define VER_MINUTE 26
#define VER_SECOND 22


#endif  // LOCONETMONITOR_BUILD_NUMBER_H
