#include "loconetthrottletestaction.h"
#include "loconetthrottletest.h"
#include "joptionpane.h"
#include "assert1.h"
#include "loggerfactory.h"
#include "junitutil.h"

LocoNetThrottleTestAction::LocoNetThrottleTestAction(QObject* parent) : AbstractAction(tr("LocoNetThrottle test"), parent)
{
    connect(this, SIGNAL(triggered()), this, SLOT(actionPerformed()));

}

void LocoNetThrottleTestAction::actionPerformed()
{
    LocoNetThrottleTest* test = new LocoNetThrottleTest();
    try
    {
     QStringList testList = QStringList()
  #if 0
         // AbstractThrottleTest
         << "testGetSpeedSetting"
         << "testSetSpeedSettingAgain"
//         << "testSetSpeedSetting"
         << "testGetIsForward"
         << "testSetIsForward"
         << "testGetF0"
         << "testGetF1"
         << "testGetF2"
         << "testGetF3"
         << "testGetF4"
         << "testGetF5"
         << "testGetF6"
         << "testGetF7"
         << "testGetF8"
         << "testGetF9"
         << "testGetF10"
         << "testGetF11"
         << "testGetF12"
         << "testGetF13"
         << "testGetF14"
         << "testGetF15"
         << "testGetF16"
         << "testGetF17"
         << "testGetF18"
         << "testGetF19"
         << "testGetF20"
         << "testGetF21"
         << "testGetF22"
         << "testGetF23"
         << "testGetF24"
         << "testGetF25"
         << "testGetF26"
         << "testGetF27"
         << "testGetF28"
         << "testGetF0Momentary"
         << "testGetF1Momentary"
         << "testGetF2Momentary"
         << "testGetF3Momentary"
         << "testGetF4Momentary"
         << "testGetF5Momentary"
         << "testGetF6Momentary"
         << "testGetF7Momentary"
         << "testGetF8Momentary"
         << "testGetF9Momentary"
         << "testGetF10Momentary"
         << "testGetF11Momentary"
         << "testGetF12Momentary"
         << "testGetF13Momentary"
         << "testGetF14Momentary"
         << "testGetF15Momentary"
         << "testGetF16Momentary"
         << "testGetF17Momentary"
         << "testGetF18Momentary"
         << "testGetF19Momentary"
         << "testGetF20Momentary"
         << "testGetF21Momentary"
         << "testGetF22Momentary"
         << "testGetF23Momentary"
         << "testGetF24Momentary"
         << "testGetF25Momentary"
         << "testGetF26Momentary"
         << "testGetF27Momentary"
         << "testGetF28Momentary"
         << "testRemovePropertyChangeListener"
         << "testAddPropertyChangeListener"
         << "testNotifyPropertyChangeListener"
         << "testGetListeners"
         << "testDispose_ThrottleListener"
         << "testDispatch_ThrottleListener"
         << "testRelease_ThrottleListener"
         << "testThrottleDispose"
         << "testGetSpeedIncrement"
         << "testSetF0Momentary"
         << "testSetF1Momentary"
         << "testSetF2Momentary"
         << "testSetF3Momentary"
         << "testSetF4Momentary"
         << "testSetF5Momentary"
         << "testSetF6Momentary"
         << "testSetF7Momentary"
         << "testSetF8Momentary"
         << "testSetF9Momentary"
         << "testSetF10Momentary"
         << "testSetF11Momentary"
         << "testSetF12Momentary"
         << "testSetF13Momentary"
         << "testSetF14Momentary"
         << "testSetF15Momentary"
         << "testSetF16Momentary"
         << "testSetF17Momentary"
         << "testSetF18Momentary"
         << "testSetF19Momentary"
         << "testSetF20Momentary"
         << "testSetF21Momentary"
         << "testSetF22Momentary"
         << "testSetF23Momentary"
         << "testSetF24Momentary"
         << "testSetF25Momentary"
         << "testSetF26Momentary"
         << "testSetF27Momentary"
         << "testSetF28Momentary"
         << "testSendMomentaryFunctionGroup1"
         << "testSendMomentaryFunctionGroup2"
         << "testSendMomentaryFunctionGroup3"
         << "testSendMomentaryFunctionGroup4"
         << "testSendMomentaryFunctionGroup5"
         << "testSetSpeedStepMode"
         << "testRecord"
         << "testStartClock"
         << "testStopClock"
         << "testFinishRecord"
         << "testSetRosterEntry"
         << "testGetRosterEntry"
         << "testGetSpeed_float"
         << "testGetSpeed_float_int"
       #endif
         // LocoNetThrottleTest
         << "testCTor"
         << "testSpeedSetting"
         << "testGetIsForward"
         << "testGetIsForward"
         << "testGetSpeedStepMode()"
         << "testGetSpeedIncrement"
         << "testGetSpeed_float"
         << "testSetF0"
         << "testSetF1"
         << "testSetF2"
         << "testSetF3"
         << "testSetF4"
         << "testSetF5"
         << "testSetF6"
         << "testSetF7"
         << "testSetF8"
         << "testSetF9"
         << "testSetF10"
         << "testSetF11"
         << "testSetF12"
         << "testSetF13"
         << "testSetF14"
         << "testSetF15"
         << "testSetF16"
         << "testSetF17"
         << "testSetF18"
         << "testSetF19"
         << "testSetF20"
         << "testSetF21"
         << "testSetF22"
         << "testSetF23"
         << "testSetF24"
         << "testSetF25"
         << "testSetF26"
         << "testSetF27"
         << "testSetF28"
         << "testSendFunctionGroup1"
         << "testSendFunctionGroup2"
         << "testSendFunctionGroup3"
         << "testSendFunctionGroup4"
         << "testSendFunctionGroup5"
            ;

     JUnitUtil::runTests(test, testList);

    }
    catch (AssertionError er)
    {
        JOptionPane::showMessageDialog(nullptr, er.getMessage(), tr("Assertion Error"), JOptionPane::WARNING_MESSAGE);
    }
}
Logger* LocoNetThrottleTestAction::log = LoggerFactory::getLogger("LocoNetThrottleTestAction");
