#include "frmabout.h"
#include "otherdata.h"

/**
 *
 * @author Gregory J. Bedlek Copyright (C) 2018, 2019
 */
// /*public*/ class FrmAbout extends JFrame {

/*private*/ /*static*/ /*final*/ QString FrmAbout::FORM_PROPERTIES = "dlgAbout";

/**
 * Creates new form dlgAbout.
 * @param awtWindowProperties window properties.
 */
/*public*/ FrmAbout::FrmAbout(AwtWindowProperties* awtWindowProperties, QWidget* parent) : JFrame(parent) {
    //super();
    initComponents();
    _mHelpTitle->setText(_mHelpTitle->text() + OtherData::CTC_VERSION);
    _mAwtWindowProperties = awtWindowProperties;
    _mAwtWindowProperties->setWindowState(this, FORM_PROPERTIES);
    //this.getRootPane().setDefaultButton(_mOK);
    _mOK->setDefault(true);
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
// <editor-fold defaultstate="collapsed" desc="Generated Code">
/*private*/ void FrmAbout::initComponents() {

    _mHelpTitle = new JLabel();
    _mOK = new JButton();
    jLabel2 = new JLabel();
    jLabel3 = new JLabel();
    jLabel4 = new JLabel();
    jLabel5 = new JLabel();
    jLabel6 = new JLabel();
    jLabel1 = new JLabel();

    setDefaultCloseOperation(JFrame::DO_NOTHING_ON_CLOSE);
    setTitle("About");
//    addWindowListener(new java.awt.event.WindowAdapter() {
//        @Override
//        /*public*/ void windowClosing(/*java.awt.event.ActionEvent evt*/) {
//            formWindowClosing(evt);
//        }
//    });
    addWindowListener(new FrmAbout_windowListener(this));

    _mHelpTitle->setText("CTCEditor - CTC Editor  ");

    _mOK->setText(tr("OK"));
//    _mOK.addActionListener(new java.awt.event.ActionListener() {
//        /*public*/ void actionPerformed(java.awt.event.ActionEvent evt) {
    connect(_mOK, &JButton::clicked, [=]{
            _mOKActionPerformed(/*evt*/);
//        }
    });

    jLabel2->setText("Developed by Gregory Bedlek");

    jLabel3->setText("With MAJOR input from the following person:");

    jLabel4->setText("Dave Sand - Really BIG help");

    jLabel5->setText("Helped me learn CTC concepts:");

    jLabel6->setText("Bob Perrin");

    jLabel1->setText("Rick Moser");
#if 0
    GroupLayout layout = new GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(54, 54, 54)
                    .addComponent(_mHelpTitle))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel3))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel5))
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel4)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(1, 1, 1)
                            .addGroup(layout.createParallelGroup(GroupLayout.Alignment.LEADING)
                                .addComponent(_mOK)
                                .addComponent(jLabel6)
                                .addComponent(jLabel1))))))
            .addContainerGap(27, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(_mHelpTitle)
            .addGap(17, 17, 17)
            .addComponent(jLabel2)
            .addGap(18, 18, 18)
            .addComponent(jLabel3)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel4)
            .addGap(18, 18, 18)
            .addComponent(jLabel5)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel1)
            .addPreferredGap(LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(jLabel6)
            .addGap(27, 27, 27)
            .addComponent(_mOK)
            .addContainerGap(36, Short.MAX_VALUE))
    );
#else
    JPanel* contentPane = new JPanel();
    contentPane->setLayout(new QVBoxLayout());
    setCentralWidget(contentPane);

    contentPane->layout() ->addWidget(_mHelpTitle);
    contentPane->layout() ->addWidget(jLabel2);
    contentPane->layout() ->addWidget(jLabel3);
    JPanel* panel1 = new JPanel(new QHBoxLayout);
    panel1->layout() ->addWidget(jLabel4);
    contentPane->layout()->addWidget(panel1);
    contentPane->layout() ->addWidget(jLabel5);
    JPanel* panel2 = new JPanel(new QHBoxLayout);
    panel2->layout() ->addWidget(jLabel1);
    panel2->layout() ->addWidget(jLabel6);
    contentPane->layout()->addWidget(panel2);
    contentPane->layout() ->addWidget(_mOK);

#endif
    pack();
}// </editor-fold>

/*private*/ void FrmAbout::formWindowClosing(QCloseEvent *evt) {
    _mAwtWindowProperties->saveWindowState(this, FORM_PROPERTIES);
    dispose();
}

/*private*/ void FrmAbout::_mOKActionPerformed(/*java.awt.event.ActionEvent evt*/) {
    _mAwtWindowProperties->saveWindowState(this, FORM_PROPERTIES);
    dispose();
}

