#include "frmfixerrors.h"
#include "commonsubs.h"
/**
 *
 * @author Gregory J. Bedlek Copyright (C) 2018, 2019
 */
// /*public*/ class FrmFixErrors extends javax.swing.JFrame {

    /*private*/ /*static*/ /*final*/ QString FrmFixErrors::FORM_PROPERTIES = "DlgFixErrors";   // NOI18N

    /*public*/ FrmFixErrors::FrmFixErrors(AwtWindowProperties* awtWindowProperties, Columns* columns, QWidget* parent) : JFrame(parent) {
        //super();
        initComponents();
        CommonSubs::addHelpMenu(this, "package.jmri.jmrit.ctc.CTC_menuEditFix", true);  // NOI18N
        _mAwtWindowProperties = awtWindowProperties;
        _mColumns = columns;
        _mAwtWindowProperties->setWindowState(this, FORM_PROPERTIES);
        //this.getRootPane().setDefaultButton(_mCancel);
        _mCancel->setDefault(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    /*private*/ void FrmFixErrors::initComponents() {

        _mInfo = new JLabel();
        jButton1 = new JButton();
        _mCancel = new JButton();

        setDefaultCloseOperation(JFrame::DO_NOTHING_ON_CLOSE);
        setTitle(tr("Fix errors"));
//        addWindowListener(new java.awt.event.WindowAdapter() {
//            @Override
//            /*public*/ void windowClosing(java.awt.event.WindowEvent evt) {
//                formWindowClosing(evt);
//            }
//        });

        _mInfo->setHorizontalAlignment(Qt::AlignCenter);
        _mInfo->setText(tr("<html>NOTE: The purpose of this routine is to go thru every column and automatically de-enable sub-system(s) that are in error. Any data that you have already entered is NOT lost, just \"ignored\".  This routine CANNOT fix missing data in the Code Button sub-system, since there is no way to de-check that.  You have two choices in this situation after this routine runs: Delete those column(s) or edit it and fix them.</html>"));
        _mInfo->setVerticalAlignment(Qt::AlignTop);
//        _mInfo->setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        _mInfo->setHorizontalTextPosition(Qt::AlignCenter);

        jButton1->setText(tr("Proceed"));
//        jButton1.addActionListener(new java.awt.event.ActionListener() {
//            @Override
//            /*public*/ void actionPerformed(/*java.awt.event.ActionEvent evt*/) {
        connect(jButton1, &JButton::clicked, [=]{
                jButton1ActionPerformed(/*evt*/);
//            }
        });

        _mCancel->setText(tr("Cancel"));
//        _mCancel.addActionListener(new java.awt.event.ActionListener() {
//            @Override
//            /*public*/ void actionPerformed(/*java.awt.event.ActionEvent evt*/) {
        connect(_mCancel, &JButton::clicked, [=]{
                _mCancelActionPerformed(/*evt*/);
//            }
        });
#if 0
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_mInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(jButton1)
                .addGap(54, 54, 54)
                .addComponent(_mCancel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(_mInfo, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(_mCancel))
                .addGap(34, 34, 34))
        );
#else
  JPanel* contentPane = new JPanel();
  QVBoxLayout* contentPaneLayout;
  contentPane->setLayout(contentPaneLayout = new QVBoxLayout());
  setCentralWidget(contentPane);

  JPanel* panel1 = new JPanel(new FlowLayout());
  panel1->layout()->addWidget(_mInfo);
  contentPaneLayout->addWidget(panel1);

  JPanel* panel2 = new JPanel(new FlowLayout());
  panel2->layout()->addWidget(jButton1);
  panel2->layout()->addWidget(_mCancel);
  contentPaneLayout->addWidget(panel2);
#endif
        pack();
    }// </editor-fold>

    /*private*/ void FrmFixErrors::formWindowClosing(QCloseEvent* evt) {
        exitDialog();
    }

    /*private*/ void FrmFixErrors::_mCancelActionPerformed(/*java.awt.event.ActionEvent evt*/) {
        exitDialog();
    }

    /*private*/ void FrmFixErrors::jButton1ActionPerformed(/*java.awt.event.ActionEvent evt*/) {
        _mColumns->fixAllErrors();
        exitDialog();
    }

    /*private*/ void FrmFixErrors::exitDialog() {
        _mAwtWindowProperties->saveWindowState(this, FORM_PROPERTIES);
        dispose();
    }
